<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vitepress';
import PreReleaseNotice from './PreReleaseNotice.vue';

// The API reference is generated by TypeDoc into site/api/ with
// `cleanOutputDir`, so the notice cannot live in those markdown files, it
// would be wiped on the next `npm run docs:api:site`. It is injected through
// the layout's `doc-before` slot instead, matched on the route.
const route = useRoute();
const onApiPage = computed(() => route.path.startsWith('/api/'));
</script>

<template>
  <PreReleaseNotice v-if="onApiPage" />
</template>
